# Generated by Django 2.1 on 2018-10-07 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamejackpot',
            name='bet',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
