# Generated by Django 2.1 on 2018-10-07 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0002_auto_20181007_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamejackpot',
            name='spin',
        ),
        migrations.AddField(
            model_name='gamejackpot',
            name='counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
