# Generated by Django 2.1 on 2018-10-07 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0003_auto_20181007_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejackpot',
            name='win_counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
